- name: Import cleanup playbook
  import_playbook: _subpbook_cleanup.yml

- name: Get commited configuration of devices
  hosts: all
  roles:
    - Juniper.junos
  gather_facts: no

  tasks:

    - name: Retrieve config + save at ~/ansible_tmp/{hostname}/{hostname}.xml
      juniper_junos_config:
        retrieve: "committed"
        format: "xml"
        dest_dir: "{{ base_dir }}"
#      register: response
#    - name: Print result
#      debug:
#        var: response.config_lines
