---
- name: 'Push Config to Device & Commit/Check'
  juniper_junos_config:
    mode: '{{ connect_mode if connect_mode is defined else omit }}'
    port: '{{ connect_port if connect_port is defined else omit }}'
    src: '{{ junos_conf }}'
    config_mode: '{{ config_mode if config_mode is defined else omit }}'
    load: 'update'
    timeout: '300'
    commit: '{{ commit }}'
    confirm: '{{ confirm if confirm is defined else omit }}'
    diffs_file: '{{ compare_conf }}'
  register: response

- name: 'Output diff if changes are present, else skip:'
  debug:
    var: response.diff_lines
  when: response.diff_lines is defined

- name: 'Message from juniper_junos_config:'
  debug:
    var: response.msg
